"""Subclass of LongHuConceptBaseForm, which is generated by wxFormBuilder."""

import wx
import MainForm

# Implementing LongHuConceptBaseForm
class LongHuConceptForm( MainForm.LongHuConceptBaseForm ):
	def __init__( self, parent ):
		MainForm.LongHuConceptBaseForm.__init__( self, parent )

