# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1355, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateTimeEdit_Update_StartTime = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_Update_StartTime.setDate(QtCore.QDate(2019, 1, 1))
        self.dateTimeEdit_Update_StartTime.setObjectName("dateTimeEdit_Update_StartTime")
        self.horizontalLayout.addWidget(self.dateTimeEdit_Update_StartTime)
        self.dateTimeEdit_Update_EndTime = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_Update_EndTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_Update_EndTime.setDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_Update_EndTime.setObjectName("dateTimeEdit_Update_EndTime")
        self.horizontalLayout.addWidget(self.dateTimeEdit_Update_EndTime)
        self.pushButton__UpdateDateBase = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__UpdateDateBase.setObjectName("pushButton__UpdateDateBase")
        self.horizontalLayout.addWidget(self.pushButton__UpdateDateBase)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_stockbasic = QtWidgets.QTableView(self.layoutWidget)
        self.tableView_stockbasic.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableView_stockbasic.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableView_stockbasic.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableView_stockbasic.setObjectName("tableView_stockbasic")
        self.verticalLayout.addWidget(self.tableView_stockbasic)
        self.pushButton_filter = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.verticalLayout.addWidget(self.pushButton_filter)
        self.pushButton_reset_stockbasic = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset_stockbasic.setObjectName("pushButton_reset_stockbasic")
        self.verticalLayout.addWidget(self.pushButton_reset_stockbasic)
        self.checkBox_kechuangban = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_kechuangban.setChecked(True)
        self.checkBox_kechuangban.setObjectName("checkBox_kechuangban")
        self.verticalLayout.addWidget(self.checkBox_kechuangban)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_sharename_filter = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sharename_filter.setObjectName("lineEdit_sharename_filter")
        self.horizontalLayout_3.addWidget(self.lineEdit_sharename_filter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_filer_industry = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_filer_industry.setObjectName("lineEdit_filer_industry")
        self.horizontalLayout_5.addWidget(self.lineEdit_filer_industry)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_concept = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_concept.setObjectName("comboBox_concept")
        self.horizontalLayout_6.addWidget(self.comboBox_concept)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dateEdit_listdate = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_listdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_listdate.setObjectName("dateEdit_listdate")
        self.horizontalLayout_2.addWidget(self.dateEdit_listdate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(410, 10, 334, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_cur_tscode = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_cur_tscode.setObjectName("lineEdit_cur_tscode")
        self.horizontalLayout_4.addWidget(self.lineEdit_cur_tscode)
        self.lineEdit_cur_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_cur_name.setObjectName("lineEdit_cur_name")
        self.horizontalLayout_4.addWidget(self.lineEdit_cur_name)
        self.widget_chartview = QtWidgets.QWidget(self.centralwidget)
        self.widget_chartview.setGeometry(QtCore.QRect(410, 60, 911, 391))
        self.widget_chartview.setObjectName("widget_chartview")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1355, 23))
        self.menubar.setObjectName("menubar")
        self.menu__command = QtWidgets.QMenu(self.menubar)
        self.menu__command.setObjectName("menu__command")
        self.menu_aboat = QtWidgets.QMenu(self.menubar)
        self.menu_aboat.setObjectName("menu_aboat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdateDataBase = QtWidgets.QAction(MainWindow)
        self.actionUpdateDataBase.setCheckable(False)
        self.actionUpdateDataBase.setObjectName("actionUpdateDataBase")
        self.menu__command.addAction(self.actionUpdateDataBase)
        self.menubar.addAction(self.menu__command.menuAction())
        self.menubar.addAction(self.menu_aboat.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton__UpdateDateBase.clicked.connect(MainWindow.slot_UpdateDataBase)
        self.tableView_stockbasic.clicked['QModelIndex'].connect(MainWindow.slot_StockBasicClick)
        self.checkBox_kechuangban.stateChanged['int'].connect(MainWindow.slot_KechuangbanClick)
        self.pushButton_filter.clicked.connect(MainWindow.slot_filer_stockbasic)
        self.pushButton_reset_stockbasic.clicked.connect(MainWindow.slot_reset_stockbasic)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dateTimeEdit_Update_StartTime.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.dateTimeEdit_Update_EndTime.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.pushButton__UpdateDateBase.setText(_translate("MainWindow", "更新数据库"))
        self.pushButton_filter.setText(_translate("MainWindow", "筛选"))
        self.pushButton_reset_stockbasic.setText(_translate("MainWindow", "重置"))
        self.checkBox_kechuangban.setText(_translate("MainWindow", "包含科创板"))
        self.label_2.setText(_translate("MainWindow", "名称筛选:"))
        self.label_4.setText(_translate("MainWindow", "经营范围:"))
        self.label_5.setText(_translate("MainWindow", "概念："))
        self.label.setText(_translate("MainWindow", "上市时间小于:"))
        self.dateEdit_listdate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_3.setText(_translate("MainWindow", "当前选择:"))
        self.menu__command.setTitle(_translate("MainWindow", "命令"))
        self.menu_aboat.setTitle(_translate("MainWindow", "关于"))
        self.actionUpdateDataBase.setText(_translate("MainWindow", "UpdateDataBase"))
