"""Subclass of MainForm, which is generated by wxFormBuilder."""

import wx
import MainForm

# Implementing MainForm
class StockFormMainForm( MainForm.MainForm ):
	def __init__( self, parent ):
		MainForm.MainForm.__init__( self, parent )

if __name__ == '__main__':
	App = wx.App(False)
	Form = StockFormMainForm(None)
	Form.Show()
	App.MainLoop()
